
language: r

env:
  global:
    - secure: iJfBjWrfTe5SL+yq+2lnbtc1lmxcqTUUQ5pW7xxBVq53r+GGIJ2Pk/RnOFtSR7K2RFHGTdYbqlQVynep/B981DXyNW8NQL/B7BWhrmpWOFGBBM9sPNNTuu59qrX57gfKtlePFr7ptHAqXSN9eNZGniVlAcM31ewJ3w/44UhlsvjBxjJRv+ZoH3/ZjTmP6JDUutnFJRfrjrtFz0rkDHug1spKH4vHMzq7nqRsHOdxOmTWdUGSURtzOANR8SkbIWEG5Wr8zK7sz/mBIfixG5OzxilMsmlNdX6UfVxxLSbOdbmUZFlJ58ij8fvCUc7XvV9Gd2/rDmqIleRZh37JTVT3mh7cpRnMhLekRZyn0DPRPMjYwGkhfK5V+tOwlvKoY83bjXKpwDBPvSfuW8p73fFu3A9/QmXSDg/DVvjXUiu8xy46Au3h0SNFKJ6ds1t3rc8K3eDKTdk5cCvush+/r/FTRcWc7MtaGRTuo+hbv9WWqBDXU1zGbU745eEo4P551LUH0v7YOtziiuNi99gxnT9/VBes7VA8FtqvNa7Hh7bsTAjlXwuSL75uTVJAzL6rHtv900PGElKIBop5SIiSWyNu4bYl0SRZ6mOdtP1S7aa6tyWs6V29a76n32KIpwgGeUCe1KoTfRxQwl/QMxIJekMR09ar6f9JC7QO4vbapSuXF/g=

before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
  - ./_deploy.sh
